# Generated by Django 2.2 on 2021-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0002_auto_20210320_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
